export const OFFLINE_WRITE_STARTED_CODE = 'OFFLINE_WRITE_STARTED';
export const OFFLINE_RESULT_UNKNOWN_CODE = 'OFFLINE_RESULT_UNKNOWN';
export const UNRESOLVED_OFFLINE_CODES = [
  OFFLINE_WRITE_STARTED_CODE,
  OFFLINE_RESULT_UNKNOWN_CODE,
] as const;

export const OFFLINE_BATCH_ACTIONS = ['offline', 'cleanup'] as const;
